### ISSUE TITLE
lib could not be found in the same place

### ISSUE THREAD

**Issue by diversys** [adamfowleruk/Paladin#344]
Opening Paladin.pld on x86_64 brings up the following alert:
![image](https://user-images.githubusercontent.com/1316513/71603308-48247580-2b6d-11ea-9b9e-3c97e6f98d88.png)

Not sure what HaikuGCC4 is, especially since we switched to `GCC 8` after beta1. Also path for this library shouldn't have changed at all.

**Comment by adamfowleruk** [comment]
Yeah this is a warning hangover. In the file it has a placeholder for the paths.

**Comment by adamfowleruk** [comment]
Fixed in develop. See #352
