### ISSUE TITLE
Paladin does not build with latest Haiku Release

### ISSUE THREAD

**Issue by mbrumbelow** [adamfowleruk/Paladin#380]
Latest Paladin builds on hrev55602 x86_64 with the following:

g++ -c AsciiWindow.cpp -iquote./  -iquote./  -iquoteBuildSystem/  -iquotePreviewFeatures/  -iquoteSourceControl/  -iquoteThirdParty/  -iquoteobjects.x86_64-cc8-release/   -O1   -D_ZETA_TS_FIND_DIR_ -std=c++0x  -o "objects.x86_64-cc8-release/AsciiWindow.o"
AsciiWindow.cpp: In constructor 'AsciiWindow::AsciiWindow()':
AsciiWindow.cpp:198:3: error: 'asprintf' was not declared in this scope
   asprintf(&row, "  %3d   %2x  %3o   %3s  %s", i, i, i,
   ^~~~~~~~
AsciiWindow.cpp:198:3: note: suggested alternative: 'vsprintf'
   asprintf(&row, "  %3d   %2x  %3o   %3s  %s", i, i, i,
   ^~~~~~~~
   vsprintf
/boot/system/develop/etc/makefile-engine:300: recipe for target 'objects.x86_64-cc8-release/AsciiWindow.o' failed
make: *** [objects.x86_64-cc8-release/AsciiWindow.o] Error 1

Looks like the Makefile needs to be told more information about stdlib in order to compile correctly.

**Comment by adamfowleruk** [comment]
Hmmm that's super annoying. Might be due to an assumed include. Probably not hard to fix... Will add it to the list. Thanks!

**Comment by korli** [comment]
using -std=c++0x doesn't include gnu extensions probably.

**Comment by mbrumbelow** [comment]
It compiles and runs with _GNU_SOURCE defined on x86 and x86_64.

**Comment by korli** [comment]
or use -std=gnu++0x

**Comment by meatpi** [comment]
I had the same issue, but I rebuilt Paladin using the buildscript and it seems fine now

**Comment by mbrumbelow** [comment]
Closed
